# coding: utf-8

"""
    LocalStack REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2026.6.0
    Contact: info@localstack.cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from localstack.sdk.models.replication_job_resources import ReplicationJobResources
from typing import Optional, Set
from typing_extensions import Self

class ReplicationJob(BaseModel):
    """
    ReplicationJob
    """ # noqa: E501
    job_id: Optional[StrictStr] = Field(default=None, description="The Id of the ReplicationJob.")
    state: Optional[StrictStr] = Field(default=None, description="State of the ReplicationJob.")
    error_message: Optional[StrictStr] = Field(default=None, description="Description of failure in case of failed replication.")
    type: Optional[StrictStr] = Field(default=None, description="Type of replication Job.")
    replication_config: Optional[Dict[str, Any]] = Field(default=None, description="configuration object for custom replication")
    explore_strategy: Optional[StrictStr] = Field(default='SIMPLE', description="defines the exploration strategy used for the replication job")
    resources: Optional[ReplicationJobResources] = None
    __properties: ClassVar[List[str]] = ["job_id", "state", "error_message", "type", "replication_config", "explore_strategy", "resources"]

    @field_validator('explore_strategy')
    def explore_strategy_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['SIMPLE', 'TREE']):
            raise ValueError("must be one of enum values ('SIMPLE', 'TREE')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ReplicationJob from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of resources
        if self.resources:
            _dict['resources'] = self.resources.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ReplicationJob from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "job_id": obj.get("job_id"),
            "state": obj.get("state"),
            "error_message": obj.get("error_message"),
            "type": obj.get("type"),
            "replication_config": obj.get("replication_config"),
            "explore_strategy": obj.get("explore_strategy") if obj.get("explore_strategy") is not None else 'SIMPLE',
            "resources": ReplicationJobResources.from_dict(obj["resources"]) if obj.get("resources") is not None else None
        })
        return _obj


