# coding: utf-8

"""
    LocalStack REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2026.6.0
    Contact: info@localstack.cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from localstack.sdk.models.replication_supported_resource_batch import ReplicationSupportedResourceBatch
from localstack.sdk.models.replication_supported_resource_resource_tree import ReplicationSupportedResourceResourceTree
from localstack.sdk.models.replication_supported_resource_single import ReplicationSupportedResourceSingle
from typing import Optional, Set
from typing_extensions import Self

class ReplicationSupportedResource(BaseModel):
    """
    ReplicationSupportedResource
    """ # noqa: E501
    resource_type: StrictStr = Field(description="Type of resource")
    service: StrictStr = Field(description="AWS service.")
    single: Optional[ReplicationSupportedResourceSingle] = None
    batch: Optional[ReplicationSupportedResourceBatch] = None
    resource_tree: Optional[ReplicationSupportedResourceResourceTree] = None
    extra_config: Optional[Dict[str, Any]] = Field(default=None, description="Used to expose extra configuration item when replicating a specific resource. Those are extra keys that can be sent in the `replication_job_config` object")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["resource_type", "service", "single", "batch", "resource_tree", "extra_config"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ReplicationSupportedResource from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of single
        if self.single:
            _dict['single'] = self.single.to_dict()
        # override the default output from pydantic by calling `to_dict()` of batch
        if self.batch:
            _dict['batch'] = self.batch.to_dict()
        # override the default output from pydantic by calling `to_dict()` of resource_tree
        if self.resource_tree:
            _dict['resource_tree'] = self.resource_tree.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ReplicationSupportedResource from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "resource_type": obj.get("resource_type"),
            "service": obj.get("service"),
            "single": ReplicationSupportedResourceSingle.from_dict(obj["single"]) if obj.get("single") is not None else None,
            "batch": ReplicationSupportedResourceBatch.from_dict(obj["batch"]) if obj.get("batch") is not None else None,
            "resource_tree": ReplicationSupportedResourceResourceTree.from_dict(obj["resource_tree"]) if obj.get("resource_tree") is not None else None,
            "extra_config": obj.get("extra_config")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


