name: Release LocalStack Python Client

on:
  workflow_dispatch:
    inputs:
      version:
        description: The version of the OpenAPI spec to release the client for
        required: true

env:
  TAG_VERSION: "${{ inputs.version }}"
  git_user_name: localstack[bot]
  git_user_email: localstack-bot@users.noreply.github.com

jobs:

  test_python:
    runs-on: ubuntu-latest

    steps:
    - name: Verify OpenAPI version
      run: |
        SPEC_URL=https://github.com/localstack/openapi/releases/download/${{ env.TAG_VERSION }}/localstack-spec.yml
        # Check if the URL is valid
        if ! wget --spider -q "$SPEC_URL"; then
          echo "Invalid spec to build from: $SPEC_URL. Aborting ..."
          exit 1
        fi
        
        echo "VERSION=${TAG_VERSION#v}" >> $GITHUB_ENV

    - name: Pull image
      run: |
        docker pull localstack/localstack-pro:${VERSION}

    - name: Checkout
      uses: actions/checkout@v4
      with:
        # setuptools_scm requires git history to determine the version
        fetch-depth: 0

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install uv
      uses: astral-sh/setup-uv@v3

    - name: Generate code from spec
      run: |
        make clean-generated
        ./bin/generate https://github.com/localstack/openapi/releases/download/${{ env.TAG_VERSION }}/localstack-spec.yml

    - name: Install project
      run: |
        make install-dev

    - name: Install LocalStack
      run: |
        pip install localstack==${{ env.TAG_VERSION }}

    - name: Start Localstack
      env:
       LOCALSTACK_AUTH_TOKEN: ${{ secrets.LOCALSTACK_AUTH_TOKEN }}
      run: |
          source .venv/bin/activate
          DEBUG=1 DISABLE_EVENTS="1" IMAGE_NAME="localstack/localstack-pro:${VERSION}" localstack start -d
          localstack wait -t 120 || (python -m localstack.cli.main logs && false)

    - name: Run Python Tests
      env:
        LOCALSTACK_AUTH_TOKEN: ${{ secrets.LOCALSTACK_AUTH_TOKEN }}
      run: |
        make test

    - name: Stop Localstack
      if: always()
      run: |
          source .venv/bin/activate
          localstack logs
          localstack stop

    - name: Install release helper
      run: |
        curl -o bin/release-helper.sh -L https://api.github.com/repos/localstack/localstack/contents/bin/release-helper.sh -H 'Accept: application/vnd.github.v3.raw'
        chmod +x bin/release-helper.sh

    - name: Create the release commit and tag
      run: |
        bin/release-helper.sh git-commit-release ${{ env.TAG_VERSION }}

    - name: Publish release to pypi
      run: |
        make clean && make install
        make publish
      with:
        UV_PUBLISH_TOKEN: ${{ secrets.UV_PUBLISH_TOKEN }}

    - name: Push the release commit and tag
      run: |
        git push --follow-tags

    - name: Create GitHub release
      env:
        GITHUB_TOKEN: ${{ secrets.LOCALSTACK_GITHUB_TOKEN }}
      run: gh release create "${{ env.TAG_VERSION }}" --generate-notes --draft

    - name: Commit and push next development version
      run: |
        bin/release-helper.sh git-commit-increment
        git push

    - name: Publish development version to pypi
      run: make install && make publish

    - name: "Show git modifications"
      run: |
        git log --oneline -n 3
        git show HEAD~1
        git show HEAD